spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/salon?useSSL=false&serverTimezone=UTC
    username: root
    password: Mint@0031
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true